# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  # configure resolvers
  resolvers:
    # setup the default resolver
    default:
      # use the default web path
      web_path: ~

  filter_sets:
    my_thumb:
      filters:
        thumbnail:
          size: [200, 200]
          mode: outbound
          allow_upscale: true
