# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

#  loaders:
#    flysystem_loader:
#      flysystem:
#        filesystem_service: oneup_flysystem.public_filesystem_filesystem
#  # default loader to use for all filter sets
#  data_loader: flysystem_loader

  # configure resolvers
  resolvers:
    # setup the default resolver
    default:
      # use the default web path
      web_path: ~

  filter_sets:
    my_thumb:
      filters:
        thumbnail:
          size: [200, 200]
          mode: outbound
          allow_upscale: true
